### ISSUE TITLE
Sublime Text 3 Support

### ISSUE THREAD

**Issue by segiddins** [titoBouzout/WordCount#10]

**Comment by jbrooksuk** [comment]
I'd do it but I'm not sure what's required to make these changes - I'm a _bit_ behind.

**Comment by segiddins** [comment]
If you want I could look into it

-Samuel E. Giddins
segiddins.me

On Feb 27, 2013, at 4:57 AM, James Brooks notifications@github.com wrote:

I'd do it but I'm not sure what's required to make these changes - I'm a bit behind.

**Comment by alehandrof** [comment]
It's working just fine for me. There was an [error on installation that was related to Package Control](https://github.com/wbond/sublime_package_control/issues/307). Updating Package Control resolves that issue. (WordCount still worked.)

**Comment by FichteFoll** [comment]
Well, it shouldn't work. I guess you updated on the fly and didn't restart because the API is not available at load time and would result in an exception on [line 16](https://github.com/SublimeText/WordCount/blob/master/WordCount.py#L16).

**Comment by alehandrof** [comment]
Yup, you're absolutely right. Sorry about that. Should not post "helpful" comments when I have a looming deadline and am just trying to figure out how many words I've left :)

**Comment by titoBouzout** [comment]
To many words, so little pull request..

**Comment by titoBouzout** [comment]
Done.

**Comment by segiddins** [comment]
Going to merge the pull request?

**Comment by titoBouzout** [comment]
¿?

**Comment by titoBouzout** [comment]
There is https://github.com/SublimeText/WordCount/tree/st3

**Comment by segiddins** [comment]
But it can't be installed from package control… On the whole not a big deal.

**Comment by titoBouzout** [comment]
There is some progress in PC I believe to allow manage this mess of versions. Please be patient :)

**Comment by alehandrof** [comment]
You can add repos in PC. It's not well-advertised, but you can add _branches_ using this command. So, just go ahead and add `https://github.com/SublimeText/WordCount/tree/st3`. Then, install WordCount as you normally would.

There are issues with packages that need to access their contents (because PC installs them as .sublime-package archives). These you should clone to Packages manually.

Hope this helps.

**Comment by pentago** [comment]
For some reason WordCound doesn't work on new build, might need looking into it..

**Comment by titoBouzout** [comment]
Works for me, which sublime version? which wordcount? 
ST3 https://github.com/SublimeText/WordCount/tree/st3

**Comment by pentago** [comment]
Latest st3 beta, wordcount from package control.. Any ideas?

**Comment by titoBouzout** [comment]
Yes, download this version  https://github.com/SublimeText/WordCount/tree/st3
Package control downloads the ST2 version

**Comment by pentago** [comment]
Ahhh, sure, will try and report back. Thanks a ton!

**Comment by pentago** [comment]
Yeah, it works, thanks :)

**Comment by jbrooksuk** [comment]
This had stopped working recently, #14 but I've fixed it in 5b65c7bbf996ca137d1ab9143aa9ca732769fdb4.
