### ISSUE TITLE
Not in PC anymore?

### ISSUE THREAD

**Issue by rsertelon** [titoBouzout/WordCount#11]
Hi,

It seems that WordCount is not supplied by Package Control anymore (cannot find it here : http://wbond.net/sublime_packages/community nor in my PC).

Is it normal, did I miss something?

Thanks!

**Comment by FichteFoll** [comment]
Screenshots just taken:

![image](http://i.imgur.com/3VuzQIb.png)

![image2](http://i.imgur.com/auSaqfO.png)

**Comment by rsertelon** [comment]
True, sorry for bothering you, now I have it. Maybe my web connection in ST2 was broken somehow ^^

**Comment by FichteFoll** [comment]
It's weird though that searching on the webpage also did not work.

**Comment by rsertelon** [comment]
I agree, maybe it was really missing for some minutes...
