### ISSUE TITLE
Does not load after restart on Sublime Text 3

### ISSUE THREAD

**Issue by nashv** [titoBouzout/WordCount#14]
When Wordcount is installed via the Package Manager, it immediately updates the Status bar and shows the word count.

Upon restart, word count is not visible.

**Comment by jbrooksuk** [comment]
WordCount is currently not ST3 compatible. I'll take a look now.

**Comment by jbrooksuk** [comment]
This is now working again in 5b65c7bbf996ca137d1ab9143aa9ca732769fdb4

**Comment by titoBouzout** [comment]
I reverted commit 5b65c7b there is branch "st3" for ST3. ..

**Comment by jbrooksuk** [comment]
How come that one isn't merged yet?

**Comment by titoBouzout** [comment]
Because breaks compatibility with ST2.

**Comment by titoBouzout** [comment]
https://github.com/SublimeText/WordCount/tree/st3

**Comment by jbrooksuk** [comment]
The push I made works with ST2 and ST3.

**Comment by titoBouzout** [comment]
Probably, but you are trashing the current work of the ST3, which includes new improvements.. you should be more carefully when modifying code shared with other persons..

**Comment by jbrooksuk** [comment]
Well, I'm sorry if I managed to offend you, that wasn't my intention.

**Comment by titoBouzout** [comment]
Of course not, no offense, just be cautious :)
If there is already a branch for ST3, users should use that.. contributions more than welcome... :+1:

**Comment by jbrooksuk** [comment]
@titoBouzout Is it not worth having a working plugin for ST2 and ST3 for now, then when the st3 branch is fixed to work on ST2, bring that across? The st3 branch hasn't been worked on for 5 months.

**Comment by titoBouzout** [comment]
The ST3 branch includes improvements I'm not thinking into discarding, just to provide something installable in two versions. The ST3 branch works as we expect, it is unfortunate, that we have to split our code in two .. but well... ST2 uses python2, ,and is deprecated, I don't want to mix, things.

If I'm correctly, Package control 2, provides ways to install both versions.

**Comment by jbrooksuk** [comment]
So there is no way to get ST2 to run the ST3 branch, even without modifications?

**Comment by titoBouzout** [comment]
ST2 does not run ST3 branch. 
The ST3 branch includes async calls that ST2 does not support.

**Comment by nashv** [comment]
I am using Package Control for Sublime Text 3, and it does not indicate which branch it is using, but there seems to be only one entry for WordCount. 

Whatever branch it is installing has this bug on Sublime Text 3.

**Comment by titoBouzout** [comment]
OK, I reverted my profile.
http://www.sublimetext.com/docs/3/revert.html

Installed Package Control
https://sublime.wbond.net/installation

Menu -> Package Control -> Install Package -> WordCount

Installed the ST3 branch, and it works for me, even after restart, then the problem must be in another place.

**Comment by jbrooksuk** [comment]
@nashv upgrade Package Control to 2.0

@titoBouzout I've been able to get ST2 to work using the ST3 branch using the code [here](https://gist.github.com/jbrooksuk/6282099). I only changed it to do the `on_modified` event, but it should be similar for the rest, right?

**Comment by titoBouzout** [comment]
I'm not interested into supporting ST2. And the problem is more complex than that.. 

We will appreciate if when modifying code of the SublimeText organization you do it via pull request instead of direct push. Because changes affects current installations.

**Comment by jbrooksuk** [comment]
Why no ST2 support though? People continue to use it.

I understand, I'm not making any further pushes, you don't need to tell me again.

**Comment by titoBouzout** [comment]
The current "master" branch provides an excellent package that works with ST2.... (which will not receive any updates... because ST2 is deprecated [we have 1 guy working in a terrible editor... let's make his life more easy..])

The current "ST3" branch provides an excellent package that works with ST3... (which receives updates)

I don't want to mix the versions, because introduce a lot of noise with these if ST.version >= 3 ...

> I understand, I'm not making any further pushes, you don't need to tell me again.

Thanks a lot, much appreciated

**Comment by jbrooksuk** [comment]
Alrighty then...
