### ISSUE TITLE
Quotation marks cause inaccurate word count

### ISSUE THREAD

**Issue by leegrey** [titoBouzout/WordCount#16]
It seems that any block of characters that begins with a non-alphanumeric character is not being counted toward the word count. This means that the first word of any line of dialog, or the first word of any parenthetical statement, is being ignored. 

For example, none of these words would be counted:

"foo" 'foo' (foo) {foo}

Depending on the content, this behaviour can put the word count quite far off.

**Comment by jbrooksuk** [comment]
@leegrey which branch are you using? WordCount actually splits by one single space character. Nothing fancy goes on.

**Comment by leegrey** [comment]
Hi. I'm using the Master branch in Sublime Text 2, on OSX 10.6.8. Both the version from the package manager and from github ( the same ? ) have the same issue. Basically, if I write "foo" "foo" "foo" "foo" "foo" ( any text in quote marks ) as many times as I like it will say I have a wordcount of zero. It is not a huge deal, but it is inaccurate. @jbrooksuk - do you see the behaviour I'm describing?

**Comment by titoBouzout** [comment]
Interesting problem, I'm working into a fix

**Comment by techsmartteam** [comment]
I think has some problem also if words are separated by other white characters like tab character. Could you please check that?

**Comment by titoBouzout** [comment]
I think the problems described here are fixed. :-)

**Comment by techsmartteam** [comment]
Have you considered if a sentence contain only **&^%  *^%   #$^**? It is still 3 valid words. I proposed a new pull that solve this problem. Please have a look. Thank you.

**Comment by titoBouzout** [comment]
A real world example will help, &^% *^% #$^? is not in my dictionary. :-)

**Comment by jbrooksuk** [comment]
I could totally understand adding a fix for this if it was `SublimeText/CharacterCount` but it's words. You can get the character count by selecting all of the text. WordCount should **only ever** count actual words.

**Comment by titoBouzout** [comment]
@jbrooksuk  WordCount already counts characters too :-P hehe

**Comment by techsmartteam** [comment]
For example. if there is a line of text like this:
**{+-} + {_/} = {+-_/}**

Will the code be able to capture it and display the number of words and characters? In seems to me that it is reasonable to report that it has _5 words, 20 characters_. But the first thing is that we need to capture that line with the regular expression that accept any sequence of characters, given there is a non-space character as pointed our in the pull I proposed:

``` python
Pref.wrdRx                  = re.compile("^.*\S+.*$", re.U) 
```

What do you think?

**Comment by titoBouzout** [comment]
These are not words.

**Comment by techsmartteam** [comment]
In some software like Microsoft Word they count it :). So that is something that need to be considered. 
By the way, even if they are not words. The plugin still should report the number of characters? Doesn't it?

**Comment by titoBouzout** [comment]
Don't know, aren't you using it? :-P

**Comment by techsmartteam** [comment]
@titoBouzout : I dig into the code more than using it :D
Another option is changing **\S** as non-space character to **\w** as actually a character from **a-zA-Z0-9_** like this:

``` python
Pref.wrdRx                  = re.compile("^.*\w+.*$", re.U) 
```

**Comment by quondammelody** [comment]
This mostly works, but when it considers contractions like I'd, would've, don't, etc, they count as zero words. One way to fix this would be to change the current regex from: <code>^[^\w]?\w+[^\w]_$</code> 'to <code>^[^\w]?(\w|')+[^\w]_$</code> which counts contractions as well as things like hack'n'slash as one word (previously zero words).

**Comment by titoBouzout** [comment]
Thanks @quondammelody fixed :)

**Comment by PetaPetaPeta** [comment]
As an extension to this issue: words that start with `` are not counted as words

**Comment by titoBouzout** [comment]
which word stars with ?

```
``
```

**Comment by jbrooksuk** [comment]
@titoBouzout that's not the problem. It's when you've got a code block, say:

```
hello
```

Now `hello` doesn't count from what I understand.

**Comment by titoBouzout** [comment]
It counts

**Comment by PetaPetaPeta** [comment]
@titoBouzout I've encountered the problem in a LaTeX document where a quotation is done as: ``word''. This results in the first word in all quotations in LaTeX not being counted.

**Comment by titoBouzout** [comment]
okeii I updated the regular expression.  If you update it should work now, maybe
