### ISSUE TITLE
Word count not showing in status bar

### ISSUE THREAD

**Issue by toddprouty** [titoBouzout/WordCount#2]
I installed WordCount via Package Control but the document word count is not showing up in the status bar. Is there something else that must be done to get it working? (Sublime noob here, so bear with me if the answer is obvious.)

**Comment by titoBouzout** [comment]
MMmm :)

Did you installed "Package Control" ?
If yes, are you sure is enabled?
I can't think something else now.

**Comment by hawkrives** [comment]
Could you go to `Preferences>Browse Packages` and check to make sure that there is a folder called `WordCount`? 

I'm thinking that it must have somehow not been installed; it's always been install 'n run for me.

**Comment by toddprouty** [comment]
I did install this through Package Control. For some reason removing and re-installing (again, through Package Controller) fixed it. Guess I should have tried that first!
