### ISSUE TITLE
Don't count white space characters

### ISSUE THREAD

**Issue by bennyrowland** [titoBouzout/WordCount#24]
When writing a document subject to a character limit, it is common that characters such as space, new line etc. should not be included in the character count. It would be nice to see this as an option for character counting, or even better to have a way to define a list of characters which should not be counted.

**Comment by titoBouzout** [comment]
Sorry for delay, now it does not count whitespace characters. https://github.com/SublimeText/WordCount/commit/2913e7e7d6bd965991142aad4103084097f397ba

**Comment by titoBouzout** [comment]
The other options are possible, but I'm feel lazy now :P haha
