### ISSUE TITLE
Package Control: The package "WordCount" is not available on this platform.

### ISSUE THREAD

**Issue by zbrox** [titoBouzout/WordCount#25]
I get the following error when I try to install WordCount

`Package Control: The package "WordCount" is not available on this platform.`

This is when trying to install through an updated Package Control on SublimeText 3 build 3061 on OS X Mavericks.

**Comment by titoBouzout** [comment]
Mmmmh.... try removing and reinstalling.

**Comment by zbrox** [comment]
Unfortunately there's nothing to remove. This message is on install and after that I don't get anything in the Packages or Installed Packages folders.

**Comment by titoBouzout** [comment]
Try revertinig, http://www.sublimetext.com/docs/3/revert.html
At least temporarily, it should just work.

**Comment by zbrox** [comment]
Thanks! I started with a fresh data folder and the install went just fine. I guess some other plugin was making problems somehow.

**Comment by jbrooksuk** [comment]
If you reinstall your plugins one-by-one and notice one that causes the issue please let us know and we can try resolve the issue.

**Comment by zbrox** [comment]
Unfortunately I got nothing. I uninstalled every plugin and after each removal I tried to install WordCount but to no avail. I tried to clean the cache folder as a random attempt at something but still the results are the same. Sorry I couldn't be of any help.

**Comment by madrobby** [comment]
I have exactly the same problem (SublimeText 3/Mac), `The package "WordCount" is not available on this platform.`.

Here's my package control user settings, if that is of any help:

```
{
    "auto_upgrade_last_run": null,
    "installed_packages":
    [
        "CoffeeScript",
        "Color Highlighter",
        "DashDoc",
        "GitGutter",
        "HexViewer",
        "Live CSS",
        "nginx",
        "Package Control",
        "RubyMotionBuilder",
        "RubyTest",
        "SublimeHighlight",
        "TrailingSpaces"
    ],
    "repositories":
    [
        "https://github.com/n1k0/SublimeHighlight/tree/python3",
        "https://github.com/SublimeText/WordCount/tree/st3"
    ]
}
```

**Comment by titoBouzout** [comment]
Try removing the package and installing it again. I would also remove the custom repository set. As this package is included in package control.

**Comment by madrobby** [comment]
The package doesn't show up to be installed if the extra repository is not given. I've the latest ST 3 version and reinstalled package control.

**Comment by titoBouzout** [comment]
Then maybe is probably disabled or something like that. It should show up.

**Comment by titoBouzout** [comment]
You may also want to try reverting, if you have been testing things, and installing packages manually  in ST http://www.sublimetext.com/docs/3/revert.html

**Comment by fox354** [comment]
Hi! 
When I run the ST3 I get the message: "The package" WordCount "is not available"
Also located on site Package Control Word Count addition has the status of "Removed"
Why? It was very handy addition!

PS: it works if you copy the directory manually: ..\Sublime Text 3\Packages\
