### ISSUE TITLE
wrdRX option

### ISSUE THREAD

**Issue by PMunch** [titoBouzout/WordCount#26]
When writing documents in TeX or it's derivatives (e.g. LaTeX) you use tags to control how the document would appear when rendered. These tags can get numerous and as they don't appear in the final document they wouldn't traditionally be counted as a word. Take the example from [Wikipedia](http://en.wikipedia.org/wiki/TeX#Mathematical_example) as example:

```
The quadratic formula is $-b \pm \sqrt{b^2 - 4ac} \over 2a$
\bye
```

This is considered by word count to be nine words. The rendered output however is:

```
The quadratic formula is <formula>
```

This would normally be counted to be either four or five words.

This makes writing word dependent documents in TeX etc. ambiguous. My proposition is to either expose wrdRX in full through the settings, or to expose the uses of \w and [^\w] as two separate settings.

**Comment by titoBouzout** [comment]
Done :)
