### ISSUE TITLE
Using .split() makes regex checking for comments impossible

### ISSUE THREAD

**Issue by PMunch** [titoBouzout/WordCount#27]
Following my previous issue making wrdRx changeable in settings I've encountered another problem with using WordCount and custom wrdRx expressions. Say for example you wish to remove a comment:

```
Text here %This is a comment
```

The comment would be split into individual words, making it indistinguishable from other words. So I propose adding a splitRx, to control how the text is split. I've used it successfully on my install with a regex that simply picks up LaTeX specific tags as a single element which won't pass the wrdRx test. I've tested both for speed on a ~900 word LaTeX document 100 times and I don't get any severe performance decrease.

**Comment by titoBouzout** [comment]
Problem is that python will not split with a regExp but with a string. Or I am missing something from your proposal? Maybe this http://stackoverflow.com/questions/10048017/python-split-by-regular-expression?answertab=votes#tab-top ?

**Comment by PMunch** [comment]
Yea, that's pretty much what I did. I used "findall()" with the regex "[^\s]+" (\s is equivalent to [ \t\r\n\v\f]). To replace the .replace("'",'') you can either use the regex "[^\s']+" in the split or the regex "^[\w']+$" for the word. The former counting words like don't, won't etc as two words, the latter as one. So it would be WordCount.py line 212:

```
words = len([x for x in splitRx(content) if False == x.isdigit() and wrdRx(x)])
```

Assuming of course that splitRx was initialized like wrdRx

**Comment by titoBouzout** [comment]
Alrigth, lets see https://github.com/SublimeText/WordCount/commit/5e39d8f5852a0d54773e3d7ee624bcdddbab9e96

**Comment by titoBouzout** [comment]
I also redo some optimization for big files or garbled files (if the count takes so much time to process, it will sleep longer)
Another optimization is that if you move the cursor, the count will not run. 
But.. if the selection is not empty it will run. ;)

**Comment by PMunch** [comment]
Why not just set the default splitRx to [^\s']+? That will do the same as split(content.replace("'",'')), would make the code prettier and easier to read. Not to mention people who would want to do things differently would quickly see the default way of splitting words.

I also think the readme could do with some better explanations of splitRx and wrdRx, maybe a small example would be nice.

**Comment by titoBouzout** [comment]
No, is not the same thing. As explained in the readme file, String.split with no arguments will return only non-empty portions, while find all may return empty strings. -- I accept suggestions to improve the readme.

**Comment by PMunch** [comment]
findall with the regex "[^\s]+" means all parts more than one character not containing a any whitespace character. The + ensures that no empty strings are returned as all strings must contain at least one character not in the set [^\s]. The only "empty" strings returned would be none-visible characters, and these would still occur using split.

I'll see if I can write up some good explanation of how splitRx and wrdRx works tomorrow.
