### ISSUE TITLE
Option to exclude comments

### ISSUE THREAD

**Issue by alehandrof** [titoBouzout/WordCount#28]
I would like an option to exclude comments from being counted.

I use comments in Markdown to bracket sections I'm unsure about. But then I don't have a clue how long the text is.

**Comment by jeromezero** [comment]
I second that emotion.

**Comment by jeromezero** [comment]
shouldn't it be possible to use the regular expression rules option?
if I do this:
\b(?<!)\b
it skips the first and last words in a comment ... on the right track, but not quite there

**Comment by FichteFoll** [comment]
The comment syntax is different for each language so a more general approach needs to be taken. However, if HTML is your only use case and it works fine for you, then go for it.

**Comment by alehandrof** [comment]
A more reasonable tack would be to exclude `comment` scopes from WordCount's tally, leaving the regexs to the syntax files where they belong.

**Comment by titoBouzout** [comment]
Excluding comments via scopes would be very inefficient, I added possibility to remove regexps to any syntax, check the preferences file.

**Comment by FichteFoll** [comment]
How about using `view.meta_info("shellVariables", 0)`? (refer to `Default/comment.py`)

Or alternatively `view.sel()[0].a` instead of `0`.

**Comment by titoBouzout** [comment]
The main purpose of the package is to count the total words, other features are just features. Parsing the complete file to remove all the declared comments will add a lot of overhead.

**Comment by jeromezero** [comment]
elegant solution. works like a charm!

**Comment by alehandrof** [comment]
Thank you @titoBouzout! This works just fine for my needs.

Is there any reason why in the settings file `"Markdown GFM": [...]` doesn't work, while `"markdown gfm": [...]`  does? (Or am I just daft?)

**Comment by titoBouzout** [comment]
you are welcome, the setting key should use lowercase..! May we should
anotate that somewhere :P

__
