### ISSUE TITLE
character count not displayed for selection

### ISSUE THREAD

**Issue by igordot** [titoBouzout/WordCount#30]
I just installed WordCount for Sublime Text 3. It looks like it doesn't do character counts for a selection. Is that correct?

I am including an example screenshot:
![screen shot 2014-08-21 at 12 51 07 pm](https://cloud.githubusercontent.com/assets/6363505/3999829/01dfffc0-2954-11e4-950f-cc2f48792df4.png)

 I have the entire line selected. WordCount correctly identifies that there are 16 characters on the line (whitespaces ignored). I also see that there are 41 characters selected, but that part is not generated by WordCount and does not ignore whitespaces. If I need to count the number of characters on the whole line, this is sufficient info, but not if I want to count the number of characters in a selection. Is it possible to enable that behavior?

**Comment by titoBouzout** [comment]
Done :)

**Comment by igordot** [comment]
Thanks for the quick fix!

**Comment by titoBouzout** [comment]
You are welcome!

**Comment by titoBouzout** [comment]
Now, Register ST, :P
