### ISSUE TITLE
Sublime Text 2 support

### ISSUE THREAD

**Issue by dsernst** [titoBouzout/WordCount#34]
I'm running the most up-to-date non-beta release of Sublime, 2.0.2 on OS X, and looking to add Word Count support.

From what I can tell, this plugin _used_ to support ST2, but now only supports ST3. Am I mistaken? Is there still support for ST2? Can you offer any other recommendations?

**Comment by titoBouzout** [comment]
You are right, no support for ST2. Just try to use ST3.

**Comment by jbrooksuk** [comment]
For what it's worth, Sublime Text 3 is really solid, so you should upgrade if you have an ST2 license :)

**Comment by FichteFoll** [comment]
And even if you don't have one, the public betas are usable without a license. There is actually no reason I can think of to still use ST2 besides laziness.

**Comment by jbrooksuk** [comment]
Ah yeah, I forgot that the public betas are open.
