### ISSUE TITLE
Change char_ignore_whitespace default value

### ISSUE THREAD

**Issue by entozoon** [titoBouzout/WordCount#35]
For example, if I open a file containing only
`one two three four five six seven eight nine`

It claims to be 9 Words, 36 Chars. When of course it is 44 characters.

I realise now that the char_ignore_whitespace parameter exists in order to change the way it works, but surely by default it should include whitespaces? People using this plugin would most likely be coders or copywriters where spaces count!

**Comment by titoBouzout** [comment]
ok, what  you want, is to change the default setting. I've no objection

**Comment by entozoon** [comment]
I think that would make sense :)

**Comment by titoBouzout** [comment]
See https://github.com/SublimeText/WordCount/issues/24

**Comment by titoBouzout** [comment]
confused >.<, why you opened this issue, if you then close it? hehe

**Comment by entozoon** [comment]
Because you fixed it https://github.com/SublimeText/WordCount/issues/24
