### ISSUE TITLE
for selection of numbers provide the numerical statistics

### ISSUE THREAD

**Issue by den-run-ai** [titoBouzout/WordCount#43]
for selection of numbers provide the numerical statistics: sum, average, min, max, median, UDF.

**Comment by titoBouzout** [comment]
I think this could be better handled in a Math package. Maybe here: https://packagecontrol.io/packages/Selection%20Evaluator

**Comment by den-run-ai** [comment]
The problem with MathEvaluator is inlining the results instead of
displaying it in the status bar

**Comment by titoBouzout** [comment]
every command is a separate action, ask them to just display some on
status bar

**Comment by denfromufa** [comment]
Ok, posted : https://github.com/meadowstream/MathEvaluator/issues/7
