### ISSUE TITLE
Only sublime 2?

### ISSUE THREAD

**Issue by jonathan-s** [titoBouzout/WordCount#44]
It seems like I can't find this when using sublime text 3.

**Comment by jbrooksuk** [comment]
Read the first line of the [README document](https://github.com/titoBouzout/WordCount/blob/st3/readme.md) :)

**Comment by jonathan-s** [comment]
Ooops! It'd be great if that was visible on the package control page too :)

**Comment by jbrooksuk** [comment]
![image](https://cloud.githubusercontent.com/assets/246103/7798726/90960e1e-02f5-11e5-8261-ffbed3a1923a.png)

Ah but it is. Do you already have it installed or something?

**Comment by jonathan-s** [comment]
Apparently I already have it installed! Though, I'm currently writing a document in markdown, but the wordcount is nowhere to be seen..

**Comment by jonathan-s** [comment]
Perhaps it's conflicting with gitgutter? At least that's what in the status bar below when I'm editing things.

**Comment by jonathan-s** [comment]
I uninstalled it and re-installed and that solved the issue. Seems to be working now.

**Comment by jbrooksuk** [comment]
:+1:
