### ISSUE TITLE
Incorrect counts when dashes are used

### ISSUE THREAD

**Issue by andrewheiss** [titoBouzout/WordCount#46]
The word count is _decreased_ when dashes are used. Using all the default settings, here's what the plugin reports:

```
This is a test.
# Counted: 4 words; expected: 4 words

This is—a test.
# Counted: 2 words; expected 4 words; uses an em-dash (—)

This is–a test.
# Counted: 2 words; expected 4 words; uses an en-dash (–)

This is-a test.
# Counted: 2 words; expected 4 words; uses a regular dash (-)
```

It would almost make sense if the dash decreased the count by just one, since the `is-a` could possibly be treated as a single word, but the count removes the word unit completely—it seems to only count `This` and `test`.

**Comment by andrewheiss** [comment]
This seems to possibly be related to #16…

**Comment by andrewheiss** [comment]
This can cause some pretty large discrepancies for when word counts are important:

<img width="429" alt="screen shot 2015-09-09 at 00 14 49" src="https://cloud.githubusercontent.com/assets/73663/9753221/d5fc4924-5687-11e5-81af-01b92651528f.png">

(Count of words in an actual document. Top program is [Byword](http://bywordapp.com/); bottom is Sublime Text.)

**Comment by titoBouzout** [comment]
Fixed thanks!
