### ISSUE TITLE
Can't be installed using Package Control

### ISSUE THREAD

**Issue by bosborne** [titoBouzout/WordCount#47]
Bring up Package Control: Install Package, and WordCount is not present in the dropdown. Downloading the *zip from from this repository and copying it works fine. Using Sublime Text 3, build 3083, Mac OS.

**Comment by titoBouzout** [comment]
it works must be temporal, don't install packages manually

**Comment by joosthvanderlinden** [comment]
Currently running into the same issue. Tried adding GitHub manually with "Package Control: Add Repository" but WordCount still does not show up in "Package Control: Install Package". Also using Sublime Text 3, build 3083, Mac OS.

**Comment by FichteFoll** [comment]
Temporary issue with Package Control. Refer to https://github.com/wbond/package_control/issues/1036

**Comment by diego898** [comment]
Hm. I cant see this plugin in package control anymore?

**Comment by Grawl** [comment]
The same.

**Comment by grahamannett** [comment]
yeah i uninstalled it b/c package sync gave issue and now its not in packagecontrol.
