### ISSUE TITLE
did you rebuild the repo for st3 without preserving st2?

### ISSUE THREAD

**Issue by Pomax** [titoBouzout/WordCount#51]
I found this plugin via http://sublimetexttips.com/best-plugins-for-sublime-text-2/ but the repo only has an st3 branch - did you delete the old st2 code? Because st3 never left beta, and having access to the old st2 plugin would be rather useful.

**Comment by titoBouzout** [comment]
Yes I did, ST3 has been pretty stable and already fixed many of the bugs that ST2 has. If possible you should try ST3

**Comment by Pomax** [comment]
I use both, depending on which machine I'm forced to use. Having access to the old st2 branch would still be very useful.
