### ISSUE TITLE
Cursor hiccups

### ISSUE THREAD

**Issue by martixy** [titoBouzout/WordCount#52]
This is going to seem incredibly minor, but it's also rather annoying.
In very large files(somewhere above 50-60K words), the cursor starts to "hiccup"(stop) for a moment, when moving around rapidly(i.e. like when holding down an arrow key).

**Comment by titoBouzout** [comment]
Can you please share your WorldCount settings? And if possible an example text mentioning which syntax you use.

The package already includes an incredible amount of optimizations, but I know more micro optimizations for some use-cases can be added. These gonna depend of your use-case and configuration.

**Comment by martixy** [comment]
They're the default settings. I just installed the package. And it's Plain text, just very high word count.
And it does get worse with word count. Try something with 200K words for best/worst results.

Taking a glance at the code... it runs every .4 seconds, and that seems just about the interval of the hiccups. As good as ST's regex engine is, it's probably not that good over a million characters. So I guess if there is a way to not block the app while running, or not run when not needed, that's your solution.

**Comment by titoBouzout** [comment]
ok, thanks for the information

**Comment by titoBouzout** [comment]
There I think should be fixed what you seeing. You need to update, and restart ST

**Comment by martixy** [comment]
Can confirm, it's fixed. Cursor flows smoothly over large files.
