### ISSUE TITLE
Count number of characters of current line

### ISSUE THREAD

**Issue by ghost** [titoBouzout/WordCount#6]
Hi Tito!

Optionally displaying the number of characters of the current line would be very useful when writing text for Twitter and for other limited-length text areas (such as many in web forms).

What do you think? Would you consider implementing this feature?

Be well,
Andre

**Comment by titoBouzout** [comment]
Hi Andre!

Yeah, why not, let me check..

**Comment by titoBouzout** [comment]
Done by https://github.com/SublimeText/WordCount/commit/3cb954830380b320f672f27e053deafa973358ae
Thank you

**Comment by titoBouzout** [comment]
oh sorry I missread your petition, this count words not characters.

**Comment by titoBouzout** [comment]
Now done by 580dc12

**Comment by ghost** [comment]
Thank you, Tito! :)  The only problem is that now my status bar is a bit crowded... -- Is there a way for me to hide (disable) the Line # and Column # info?

**Comment by ghost** [comment]
...Or maybe shorten the text: `Line: line_num, Column: col_num` to: `line_num:col_num` -- This would make everything easier to read and smaller...

**Comment by ghost** [comment]
...Also, consider having `line_num:col_num` at the beginning of the status bar text, rather than at the end (or middle).
