### ISSUE TITLE
Location of word count in status bar

### ISSUE THREAD

**Issue by reagle** [titoBouzout/WordCount#60]
There's a lot in my status bar, and I'd like the word count to be left most for easy sighting. Is this possible?

**Comment by titoBouzout** [comment]
Hi! there's a lot in my status bar too, not possible... I think you better ask in Sublime text forum, good luck!

**Comment by reagle** [comment]
I added a comment to [this thread](https://forum.sublimetext.com/t/more-structured-status-bar/40028).

**Comment by titoBouzout** [comment]
Thanks for the pointer
