### ISSUE TITLE
Shorten (or optionally hide) the Line # and Column # info?

### ISSUE THREAD

**Issue by ghost** [titoBouzout/WordCount#7]
Hi Tito!

(I posted these comments in that other issue I've raised, but I guess you didn't see them...)

The only problem is that now my status bar is a bit crowded... -- Is there a way for me to hide the Line # and Column # info?

...Or maybe shorten the text: `Line: line_num, Column: col_num` to: `line_num:col_num` ? -- This would make everything easier to read and smaller...

...Also, having `line_num:col_num` at the beginning of the status bar text, rather than at the end, would help.

Be well,
Andre

**Comment by titoBouzout** [comment]
ask jon about this, I don't think I will be able to do something.

Regards,
