### ISSUE TITLE
Line count for prose

### ISSUE THREAD

**Issue by ghost** [titoBouzout/WordCount#9]
Would it be easy to implement line count as well? Useful for both code and prose.

**Comment by titoBouzout** [comment]
:P

**Comment by titoBouzout** [comment]
I'll check if you don't first :)

**Comment by ghost** [comment]
From: tito
Subj: Re: [WordCount] Line count for prose (#9)

## Date: Saturday, 16-02-2013 @ 03:21 AM

> I'll check if you don't first :)

I won't first :D
I can't py... :(

**Comment by jbrooksuk** [comment]
Sorry to be the dumbass, but can you give me an example of prose and the line count it should render? I'll give it a go :+1:

**Comment by ghost** [comment]
No no, not at all. I'm probably the dumbass since I must be the only guy who wants this.
Since WordCount already provides useful information and short of having another plugin just do to one thing, I was wondering about an option to echo the exact number of lines you see before the gutter, on the status bar. No calculation has to be made, just update it when a line break is entered or removed, to be aware of the total number of lines on the current document, without having to `Command + ↓`.

eg. 400 Words/800 Chars/100 Lines

**Comment by FichteFoll** [comment]
`lines = view.rowcol(view.size())[0] + 1` if anyone wonders. Just felt like posting since I read the issue anyway.

**Comment by jbrooksuk** [comment]
@FichteFoll that's nice and easy. I didn't even get chance to check it out, nor did I know about `view.size()`
